### PR TITLE
Update replay/recordwebpage, use separate versions of replaywebpage for recording and replay

### PR DESCRIPTION
**Pull request by ikreymer**
…laywebpage for replay, instead of relying on

bundled replaywebpage pinned in archivewebpage:
- add separate replaywebpage ui and sw.js from https://cdn.jsdelivr.net/npm/replaywebpage@1.8.6/{ui.js,sw.js} as js/replaywebpage-ui.js and replay/rwp-sw.js
- parametrize using archiveweb.page or replayweb.page script via new head_insert block, set to appropriate file in record.html and results.html

### CODE REVIEW

**Comment by remram44** [comment]
I changed the webrecorder JS files to be downloaded from jsdelivr, rather than checked in into this repo. This is deployed on staging and seems to work

**Comment by remram44** [comment]
@ikreymer Is this temporary until new versions of recordwebpage come out? This means we have two copies of replaywebpage right?

**Comment by ikreymer** [comment]
A new version (0.11.1) is out now, though maybe this makes sense as gives us more flexibility. ArchiveWeb.page is dependent on ReplayWeb.page, but the two are released separately. If switching to jsdelivr, we could just have it use the latest version of each to get the latest versions

**Comment by remram44** [comment]
You're asking a reproducibility researcher to not pin his dependencies? :stuck_out_tongue_closed_eyes:

**Comment by ikreymer** [comment]
> You're asking a reproducibility researcher to not pin his dependencies? 😝

Fair enough - it did cross my mind - let's pin them :)

**Pull request merged**
