### PR TITLE
Update bootstrap to v4

### LINKED ISSUE #33: Update to Bootstrap 5
The templates were made on the previous version of bootstrap and should be updated to bootstrap 4.

### PR DESCRIPTION
**Pull request by VickyRampin**
Fixes #33 

Uses @aecio 's nifty NYU bootstrap4 theme -- thanks Aecio :heart:

### CODE REVIEW

**Comment by aecio** [comment]
FYI, there is also an additional theme that we use in Visus here: https://github.com/VIDA-NYU/nyu-bootstrap-theme/tree/master/dist/nyu-d3m It doesn't use the official NYU colors but has similar lighter colors, better fonts, and flatter design.

**Comment by VickySteeves** [comment]
Oh then wait @remram44 on reviewing this!! I like flat designs!! Thanks for the update @aecio

**Comment by aecio** [comment]
In case you prefer the original NYU colors, we could also update this `nyu` theme to use flat design and better fonts.

**Comment by VickySteeves** [comment]
I would love to update our NYU boostrap theme in the repo to have the flat design + better fonts~! Maybe it'll be my 2nd PR of Hacktoberfest :wink:

**Comment by VickySteeves** [comment]
Ready for review, @remram44 !

**Comment by remram44** [comment]
Deployed to https://staging.server.reprozip.org/

**Comment by remram44** [comment]
Thanks Vicky! Some notes:

* Links are not underlined, which makes them very difficult to see.
* The "build log" expandable container no longer has any outline:  
Screenshot_20191010_160923
* Primary buttons no longer pop out (`btn-default` class is still applied but no longer exists)
* The color is a bit of a problem because it doesn't match www.reprozip.org

**Comment by aecio** [comment]
Some comments:
- It seems that `btn-default` no longer exists in Bootstrap 4. They should be changed to either `btn-primary` or `btn-secondary`: https://getbootstrap.com/docs/4.3/components/buttons/
- This theme uses the following fonts hosted at Google Web Fonts: _Merriweather, Oswald, Source Sans Pro_. To use them, just include the following line to the HTML page:
 `<link href="https://fonts.googleapis.com/css?family=Merriweather|Oswald|Source+Sans+Pro" rel="stylesheet">`

**Pull request closed without merging**
